### PR TITLE
mh-widget 

### PR DESCRIPTION
**Pull request by packiaVaradhan**
## Proposed Changes

  The button style of the mh-widget was overridden by ruukakusaamo's css . so css is modified to handle those situation . 
 check the link to know more [ruuka.fi](https://www.ruka.fi/liikkuminen#)

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

### CODE REVIEW

**Review by Tapppi — COMMENTED** [review]
I actually don't know how to test this change locally in a reasonable fashion.. Also, I think the problem went the other way as well, i.e. our widget CSS was modifying styles of the whole ruka web page. To me it sounds like we need namespacing of all the CSS classes in our widget css? Maybe webpack has some namespacing plugin for this?

**Comment by packiaVaradhan** [comment]
> I actually don't know how to test this change locally in a reasonable fashion.. Also, I think the problem went the other way as well, i.e. our widget CSS was modifying styles of the whole ruka web page. To me it sounds like we need namespacing of all the CSS classes in our widget css? Maybe webpack has some namespacing plugin for this?



> I actually don't know how to test this change locally in a reasonable fashion.. Also, I think the problem went the other way as well, i.e. our widget CSS was modifying styles of the whole ruka web page. To me it sounds like we need namespacing of all the CSS classes in our widget css? Maybe webpack has some namespacing plugin for this?

i have modified according to your requirement and i used a test.html to test the ruuka page . i 'll share the **test .html** by slack . you can test it with that . the content of the test.html is exported from ruukas page.

**Comment by Tapppi** [comment]
@packiaVaradhan Inspired by your test page I straight up copied the source of Ruka site to test the changes with the widget. The Widget is still overriding the customer's website's styling. Our widget *must not affect any other styling on the website* except the widget. There are probably some webpack namespacing plugins to achieve this. Or so I would think.. 

See these examples for how all the fonts change and the icons even start repeating on their accommodation search:

Original:
image

With widget:
image

**Comment by tvainika** [comment]
Should the widget be exposed as `<iframe>` to avoid leaking any properties?

**Review by olavim — CHANGES_REQUESTED** [review]
- The css includes a lot of not-namespaced styles still. Also, it's simpler to namespace everything inside the `reittiopas-mh-widget` id, because we already use it to render the entire widget.

I suggest simply wrapping _all widget styles_ inside the namespace like this:
```scss
#reittiopas-mh-widget {
  ...
}
```
It makes the file much simpler.

- You now have `app/widget.scss`. Why not use the `sass` folder, which already exists, instead? I suggest moving the file to `sass/_widget.scss` to not break existing conventions in the project.

**Review by olavim — APPROVED** [review]
I didn't test the changes, but the namespacing and project structure look good to me now.

**Pull request merged**
